### ISSUE TITLE
Plugin falis to build with vst3sdk 3.7.8

### ISSUE THREAD

**Issue by burein-ita** [igorski/transformant#6]
Using Archlinux 
vst3sdk 3.7.8_build_34

Running `make` fails with the following errors:
[buildlog.txt](https://github.com/igorski/transformant/files/11713282/buildlog.txt)

This affects the other plugins as well.

Using vst3sdk 3.7.7 builds successfully.

**Comment by cbix** [comment]
Maybe one idea is to reference upstream vst3sdk in a submodule in order to pin a target version.

**Comment by igorski** [comment]
Hi all involved,

I'll use this request to update SDK version, when successful similar requests (and those relating to release tags) will be applied across all other repositories.

> Maybe one idea is to reference upstream vst3sdk in a submodule in order to pin a target version

This makes sense, previously Steinberg repository management would make this difficult to impossible, but I can have a another look to see whether things have improved.

**Comment by cbix** [comment]
> repository management would make this difficult

I would just require to clone using `git clone --recurse-submodules https://github.com/igorski/transformant`

**Comment by igorski** [comment]
As of the latest repo state, a `setup.sh` script is included which can retrieve and setup an appropriate version of the SDK locally to the project.
